### ISSUE TITLE
Burn Probability to Terra and add Future Parallelization

### ISSUE THREAD

**Issue by BadgerOnABike** [BurnP3/BurnP3Plus#1]
Working to ugrade the data management to terra and perform any parallel methods where possible.

- [x] Upgrade to Terra
~~- [ ] Add parallelization~~ Unnecessary afterall

**Comment by shreeramsenthi** [comment]
https://github.com/BurnP3/BurnP3Plus/blob/b43450217554c2ad399fa05aac5ab1f35ad758c8/src/burnProbability.R#L105-L106

The `terra::rast()` call should probably be within the `tryCatch()` in case of a missing collection of burn maps.

**Comment by shreeramsenthi** [comment]
https://github.com/BurnP3/BurnP3Plus/blob/b43450217554c2ad399fa05aac5ab1f35ad758c8/src/burnProbability.R#L116

This change does not work with the Prometheus fire growth model, as the values of pixels in the per-iteration burn maps indicate the fire ID in which the pixel was first burned, not just 1/0.

**Comment by shreeramsenthi** [comment]
Scratch that second comment, I went ahead an made that change to BurnP3Plus-Prometheus. Let me know if you'd like to change both fire models and this line if you'd like the other behaviour though.

**Comment by shreeramsenthi** [comment]
These changes and removal of RGDAL dependencies have been made to this branch and merged into main. BadgerOnABike/issue1 can probably closed now
