### ISSUE TITLE
[Burn-P3+ Bug]: SyncroSim crash on library owner change

### ISSUE THREAD

**Issue by BadgerOnABike** [BurnP3/BurnP3Plus#27]
### Contact Details

brett.moore@nrcan-rncan.gc.ca

### What happened?

When I change the owner of a library then click data feeds I get the following.
![image](https://github.com/BurnP3/BurnP3Plus/assets/10979751/1197ba12-34e0-4f3a-ab21-a1cda8f27fd9)

If I change the owner then close then go to datafeeds its fine.

### What component are you seeing the problem on?

Syncrosim

### Approvals Process

- [ ] Testing For Issue
- [ ] Merge

**Comment by BadgerOnABike** [comment]
This ONLY occurs when going to datafeeds. Other tabs do not crash it.

**Comment by BadgerOnABike** [comment]
I should mention @chittychittybangbang caught this one! I just replicated and reported :)

**Comment by katieb1** [comment]
Closing this now as it has been fixed
